"use client";
import "./studio.css";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";

export default function Studio(){
 const supabase=createClient(),router=useRouter();
 const [user,setUser]=useState<any>(null),[title,setTitle]=useState(""),[starting,setStarting]=useState(false),[error,setError]=useState("");
 useEffect(()=>{supabase.auth.getUser().then(({data:{user}})=>{if(!user)router.replace("/login");else setUser(user)})},[]);
 async function goLive(){if(!title.trim()){setError("Ajoute un titre.");return}setStarting(true);const {data,error}=await supabase.from("lives").insert({user_id:user.id,title:title.trim(),status:"live",started_at:new Date().toISOString()}).select("id").single();if(error)setError(error.message);else router.push("/studio/"+data.id);setStarting(false)}
 return <main className="studio-app"><aside className="studio-sidebar"><Link href="/" className="studio-brand">Live<span>Wave</span></Link><div className="studio-nav"><Link className="active" href="/studio">🎥 Studio</Link><Link href="/live">🔴 Lives</Link><Link href="/profile">👤 Profil</Link></div><div className="studio-side-bottom"><Link href="/profile">⚙️ Paramètres</Link></div></aside><section className="studio-main"><header className="studio-top"><div><span className="studio-kicker">LIVE STUDIO</span><h1>Préparer ton LIVE</h1></div><div className="studio-status"><i/> Prêt à diffuser</div></header><div className="studio-grid"><section className="studio-preview"><div className="preview-head"><b>Aperçu</b><span>9:16</span></div><div className="preview-phone"><div className="preview-placeholder"><div className="preview-camera">🎥</div><strong>Aperçu de ton live</strong><small>Ta caméra, ton jeu et tes overlays apparaîtront ici</small></div><div className="preview-overlay"><span>● LIVE</span><span>👁 0</span></div></div><div className="preview-controls"><span className="studio-prelaunch-note">ℹ️ Lance le LIVE pour activer les contrôles caméra, micro et jeu.</span></div></section><section className="studio-panel"><div className="studio-panel-title">Sources</div><div className="source-card source-card-disabled">📷 <div><b>Caméra + micro</b><small>Disponible dès que le LIVE est lancé</small></div><span>✓</span></div><div className="source-card source-card-disabled">🎮 <div><b>Fenêtre / jeu</b><small>Disponible dans le Studio après lancement</small></div><span>✓</span></div><div className="source-card source-card-disabled">🖼️ <div><b>Image / overlay</b><small>Disponible dans le Studio après lancement</small></div><span>✓</span></div><div className="studio-panel-title">Informations du LIVE</div><label className="studio-label">Titre</label><input className="studio-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Mon LIVE 🎮"/>{error&&<div className="studio-error">{error}</div>}<button className="studio-live-button" onClick={goLive} disabled={starting}>{starting?"Ouverture du Studio…":"🔴 Lancer le LIVE + ouvrir le Studio"}</button></section><section className="studio-chat"><div className="studio-chat-head"><b>Chat LIVE</b><span>0 spectateurs</span></div><div className="studio-chat-empty"><span>💬</span><b>Le chat apparaîtra ici</b><small>Les commentaires et interactions seront visibles pendant le LIVE.</small></div><div className="studio-bottom-tools"><button>🎁 Cadeaux</button><button>⚔️ Match</button><button>👥 Invités</button><button>🛡 Modération</button></div></section></div></section></main>
}