"use client";
import "./studio.css";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import LiveKitVideo from "@/components/livekit-video";
type Msg={id:string;body:string;user_id:string;created_at:string;username?:string|null};
export default function StudioLive(){const {id}=useParams<{id:string}>(),router=useRouter(),supabase=createClient();const[live,setLive]=useState<any>(null),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(""),[uid,setUid]=useState(""),[error,setError]=useState(""),[elapsed,setElapsed]=useState("00:00");
useEffect(()=>{let ch:any;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}setUid(user.id);const {data:l}=await supabase.from("lives").select("*").eq("id",id).single();if(!l||l.user_id!==user.id||l.status!=="live"){router.replace("/studio");return}setLive(l);const {data:rows}=await supabase.from("live_messages").select("id,body,user_id,created_at").eq("live_id",id).order("created_at",{ascending:true}).limit(100);const ids=[...new Set((rows||[]).map((x:any)=>x.user_id))];const names:Record<string,string|null>={};if(ids.length){const {data:ps}=await supabase.from("profiles").select("id,username,display_name").in("id",ids);for(const p of ps||[])names[p.id]=p.username||p.display_name}setMessages((rows||[]).map((x:any)=>({...x,username:names[x.user_id]||null})));ch=supabase.channel("studio-"+id).on("postgres_changes",{event:"INSERT",schema:"public",table:"live_messages",filter:"live_id=eq."+id},async p=>{const m=p.new as Msg;const {data:pr}=await supabase.from("profiles").select("username,display_name").eq("id",m.user_id).maybeSingle();setMessages(v=>[...v,{...m,username:pr?.username||pr?.display_name||null}].slice(-100))}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"lives",filter:"id=eq."+id},p=>{if((p.new as any).status!=="live")router.replace("/studio")}).subscribe()})();return()=>{if(ch)supabase.removeChannel(ch)}},[id]);
useEffect(()=>{if(!live?.started_at)return;const t=setInterval(()=>{const s=Math.max(0,Math.floor((Date.now()-new Date(live.started_at).getTime())/1000));setElapsed([Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,"0")).join(":"))},1000);return()=>clearInterval(t)},[live?.started_at]);
async function send(){const body=text.trim();if(!body)return;setText("");const {error:e}=await supabase.from("live_messages").insert({live_id:id,user_id:uid,body});if(e){setError(e.message);setText(body)}}async function end(){const {error:e}=await supabase.from("lives").update({status:"ended",ended_at:new Date().toISOString()}).eq("id",id).eq("user_id",uid);if(e)setError(e.message);else router.replace("/studio")}
if(!live)return <main className="studio-app"><div className="studio-loading">Chargement du Studio…</div></main>;
return <main className="studio-app"><aside className="studio-sidebar"><Link href="/" className="studio-brand">Live<span>Wave</span></Link><nav className="studio-nav"><Link className="active" href={"/studio/"+id}>🎥 Studio</Link><Link href="/live">🔴 Découvrir</Link><Link href="/profile">👤 Profil</Link></nav><div className="studio-side-bottom"><Link href="/profile">⚙️ Paramètres</Link></div></aside><section className="studio-main"><header className="studio-top"><div><span className="studio-kicker">LIVE STUDIO</span><h1>{live.title}</h1></div><div className="studio-live-state"><i/> EN DIRECT <strong>{elapsed}</strong></div></header><div className="studio-live-grid"><section className="studio-canvas-card"><div className="studio-card-head"><b>Aperçu du LIVE</b><span>9:16 · Studio</span></div><div className="studio-canvas"><LiveKitVideo liveId={id} isOwner/><div className="studio-live-badge">● LIVE</div><div className="studio-canvas-title">{live.title}</div></div><div className="studio-controls"><button>🎙️ Micro</button><button>📷 Caméra</button><button>🎮 Partager jeu</button><button onClick={()=>window.open("/live/"+id+"/chat","livewave-chat","width=380,height=700,resizable=yes")}>💬 Chat flottant</button><button className="danger" onClick={end}>⏹ Terminer</button></div></section><aside className="studio-right"><section className="studio-box"><div className="studio-box-title"><b>Sources</b><span>Actives</span></div><div className="source-row active">📷 <div><b>Caméra + micro</b><small>LiveKit · actif</small></div><span>●</span></div><div className="source-row active">🎮 <div><b>Écran / jeu</b><small>Partage disponible</small></div><span>+</span></div><div className="source-row">🖼️ <div><b>Overlay</b><small>Image de live</small></div><span>+</span></div></section><section className="studio-box chat-box"><div className="studio-box-title"><b>Chat LIVE</b><span>{messages.length}</span></div><div className="studio-chat-list">{messages.map(m=><div className="studio-chat-line" key={m.id}><strong>@{m.username||"spectateur"}</strong><span>{m.body}</span></div>)}{!messages.length&&<div className="chat-empty">Aucun commentaire.</div>}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Répondre au chat…" maxLength={500}/><button>➤</button></form></section><section className="studio-box"><div className="studio-box-title"><b>Interactions</b></div><div className="quick-grid"><button>🎁 Cadeaux</button><button>⚔️ Match</button><button>👥 Invités</button><button>🛡 Modération</button></div></section></aside></div>{error&&<div className="studio-error">{error}</div>}</section></main>}