"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import "./chat.css";
type M={id:string;body:string;user_id:string;created_at:string;username?:string|null};
export default function ChatPopup(){const {id}=useParams<{id:string}>(),router=useRouter(),supabase=createClient();const[messages,setMessages]=useState<M[]>([]),[text,setText]=useState(""),[uid,setUid]=useState(""),[title,setTitle]=useState("Chat LIVE"),[error,setError]=useState("");
 useEffect(()=>{let ch:any; (async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}setUid(user.id);const {data:live}=await supabase.from("lives").select("title,status").eq("id",id).single();if(!live||live.status!=="live"){setError("Ce live n'est plus en direct.");return}setTitle(live.title||"Chat LIVE");const {data:rows}=await supabase.from("live_messages").select("id,body,user_id,created_at").eq("live_id",id).order("created_at",{ascending:true}).limit(100);const ids=[...new Set((rows||[]).map((x:any)=>x.user_id))];const names:Record<string,string|null>={};if(ids.length){const {data:ps}=await supabase.from("profiles").select("id,username,display_name").in("id",ids);for(const p of ps||[])names[p.id]=p.username||p.display_name}setMessages((rows||[]).map((x:any)=>({...x,username:names[x.user_id]||null})));ch=supabase.channel("chat-popup-"+id).on("postgres_changes",{event:"INSERT",schema:"public",table:"live_messages",filter:"live_id=eq."+id},async p=>{const m=p.new as M;const {data:prof}=await supabase.from("profiles").select("username,display_name").eq("id",m.user_id).maybeSingle();setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,{...m,username:prof?.username||prof?.display_name||null}].slice(-150))}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"lives",filter:"id=eq."+id},p=>{if((p.new as any).status!=="live")setError("Le live est terminé.")}).subscribe()})();return()=>{if(ch)supabase.removeChannel(ch)}},[id]);
 async function send(){const body=text.trim();if(!body||!uid)return;setText("");const {error:e}=await supabase.from("live_messages").insert({live_id:id,user_id:uid,body});if(e){setError(e.message);setText(body)}}
 return <main className="chat-popup"><header><div><b>💬 Chat LIVE</b><small>{title}</small></div><button onClick={()=>window.close()}>×</button></header><section className="chat-messages">{messages.map(m=><div className="chat-message" key={m.id}><strong>@{m.username||"spectateur"}</strong><span>{m.body}</span></div>)}{!messages.length&&<div className="empty">Aucun commentaire pour le moment.</div>}</section>{error&&<div className="chat-error">{error}</div>}<form onSubmit={e=>{e.preventDefault();send()}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Écrire un commentaire…" maxLength={500}/><button>Envoyer</button></form></main>}